# Site settings
title: Alexander Svendsen
description: 'A full stack developer'
url: 'http://alexander-svendseng.ithub.com/'
baseurl: '/'
# google_analytics: 'UA-XXXXXX-X'

author:
  name: 'Alexander Svendsen'
  email: alexandersvendsen1990@gmail.com
  facebook_username: alexander.svendsen1990
  github_username:  alexander-svenden
  linkedin_username:  alexander-svendsen

# Build settings
destination: _site

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
